DEFAULT_COMMIT_INTERVAL = 5
DEFAULT_SEND_INTERVAL = 5

DEFAULT_CHUNK_SIZE = 1000

CONCURRENT_LIMIT = 10

DEFAULT_MONITOR_INTERVAL = 5

MONGO_LOG_BLOCK_INDEX = 'mongo_log_block'
MONGO_LOG_BLOCK_TYPE = 'mongo_log_block'
MONGO_ERROR_INDEX = 'mongo_error'
MONGO_ERROR_TYPE = 'mongo_error'
